/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Thu May 10 14:51:09 2018. */

#include "weather.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t weatherProto_fields[4] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, weatherProto, windSpeed, windSpeed, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, weatherProto, degree, windSpeed, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, weatherProto, precipitation, degree, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
