# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='weather.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rweather.proto\"Q\n\x0cweatherProto\x12\x0b\n\x03MPH\x18\x01 \x02(\x02\x12\x0c\n\x04KmPH\x18\x02 \x02(\x02\x12\x14\n\x0c\x63\x61lDirection\x18\x03 \x02(\x02\x12\x10\n\x08rainFall\x18\x04 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WEATHERPROTO = _descriptor.Descriptor(
  name='weatherProto',
  full_name='weatherProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MPH', full_name='weatherProto.MPH', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='KmPH', full_name='weatherProto.KmPH', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='calDirection', full_name='weatherProto.calDirection', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rainFall', full_name='weatherProto.rainFall', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['weatherProto'] = _WEATHERPROTO

weatherProto = _reflection.GeneratedProtocolMessageType('weatherProto', (_message.Message,), dict(
  DESCRIPTOR = _WEATHERPROTO,
  __module__ = 'weather_pb2'
  # @@protoc_insertion_point(class_scope:weatherProto)
  ))
_sym_db.RegisterMessage(weatherProto)


# @@protoc_insertion_point(module_scope)
