/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Thu Apr 12 15:00:21 2018. */

#include "weather.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t weatherProto_fields[5] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, weatherProto, MPH, MPH, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, weatherProto, KmPH, MPH, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, weatherProto, calDirection, KmPH, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, weatherProto, rainFall, calDirection, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
